# Generated by Django 5.1.4 on 2024-12-05 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("journeys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        default="Pending",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catering_or_chef",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="journeys.cateringorchef",
                    ),
                ),
                (
                    "extra_requests",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journeys.extrarequests",
                    ),
                ),
                (
                    "food_preferences",
                    models.ManyToManyField(to="journeys.foodpreferences"),
                ),
                (
                    "journey_preferences",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journeys.journeypreferences",
                    ),
                ),
                (
                    "paperwork_assistance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journeys.paperworkassistance",
                    ),
                ),
                (
                    "stay_preferences",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journeys.staypreferences",
                    ),
                ),
                (
                    "tour_guide_preferences",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journeys.tourguidepreferences",
                    ),
                ),
                (
                    "travel_details",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journeys.traveldetails",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle_preferences",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journeys.vehiclepreferences",
                    ),
                ),
                ("vendors", models.ManyToManyField(blank=True, to="journeys.vendor")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
